//
// Notice: This file was generated automatically by the @tjuna/config generator.
//         Do not edit this file, as change might be lost.
//

const TEST_REGEX = '(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|js?|tsx?|ts?)$';

module.exports = {
  testEnvironment: 'jsdom',
  testRegex: TEST_REGEX,
  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputDirectory: '.',
        outputName: './coverage/jest/results.xml',
      },
    ],
  ],
  collectCoverageFrom: ['**/*.{ts,tsx}'],
  coverageReporters: ['lcov', 'text'],
  coverageThreshold: {
    global: {
      branches: 40,
      functions: 40,
      lines: 40,
      statements: 40,
    },
  },
  coveragePathIgnorePatterns: [
    '<rootDir>/\\.next/',
    '<rootDir>/build/',
    '<rootDir>/node_modules/',
    '<rootDir>/*.config.js/',
    '<rootDir>/*.setup.js/',
  ],
  transform: {
    '^.+\\.(js|ts)x?$': 'babel-jest',
  },
  testPathIgnorePatterns: [
    '<rootDir>/\\.next/',
    '<rootDir>/build/',
    '<rootDir>/node_modules/',
    '<rootDir>/*.config.js',
    '<rootDir>/*.setup.js',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.ts',
    '\\.(css|scss)$': 'identity-obj-proxy',
  },
};
