//
// Notice: This file was generated automatically by the config-scripts generator.
//         Do not edit this file, as change might be lost.
//

const TEST_REGEX = '(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|js?|tsx?|ts?)$';

const PATH_DELIMITER = '[\\\\/]'; // match 2 antislashes or one slash

/**
 * On Windows, the Regex won't match as Webpack tries to resolve the
 * paths of the modules. So we need to check for \\ and /
 */
const safePath = item => item.split('/').join(PATH_DELIMITER);

module.exports = {
    setupFiles: ['<rootDir>/jest.setup.js'],
    testEnvironment: 'jsdom',
    testRegex: TEST_REGEX,
    coverageReporters: ['lcov', 'text'],
    coverageThreshold: {
        global: {
            branches: 70,
            functions: 70,
            lines: 70,
            statements: 70,
        },
    },
    coveragePathIgnorePatterns: [
        '<rootDir>/\\.next/',
        '<rootDir>/node_modules/',
        '<rootDir>/*.config.js/',
        '<rootDir>/*.setup.js/',
        '<rootDir>/analytics/',
        '<rootDir>/helpers/validation.ts',
        '<rootDir>/helpers/redirect.ts',
    ],
    transform: {
        '^.+\\.(js|ts)x?$': 'babel-jest',
    },
    transformIgnorePatterns: [
        `/node_modules/(?!${safePath(
            '@tjuna/gva-ui-components-react'
        )}).+\\.(js|ts)x?$`,
    ],
    testPathIgnorePatterns: [
        '<rootDir>/\\.next/',
        '<rootDir>/node_modules/',
        '<rootDir>/*.config.js/',
        '<rootDir>/*.setup.js/',
    ],
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
    moduleNameMapper: {
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
            '<rootDir>/__mocks__/fileMock.ts',
        '\\.(css|scss)$': 'identity-obj-proxy',
    },
};
