//
// Notice: This file was generated automatically by the @tjuna/config generator.
//         Do not edit this file, as change might be lost.
//         If you want custom next.config.js settings, create a ./next.config.custom.js file
//

// eslint-disable-next-line @typescript-eslint/no-var-requires
const withSourceMaps = require('@zeit/next-source-maps');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withProgressBar = require('next-progressbar');

require('dotenv').config();

let customConfig;

try {
  // eslint-disable-next-line global-require
  customConfig = require('./next.config.custom');
} catch (e) {
  customConfig = {};
}

const nextConfig = {
  distDir: '.next',
  webpack(originalConfig, options) {
    const config = {
      ...originalConfig,
      node: {
        fs: 'empty',
      },
    };

    if (!options.isServer) {
      config.resolve.alias['@sentry/node'] = '@sentry/browser';
    }

    return config;
  },
};

module.exports = withSourceMaps(
  withProgressBar({
    ...nextConfig,
    ...customConfig,
  })
);
