//
// Notice: This file was generated automatically by the @tjuna/config generator.
//         Do not edit this file, as change might be lost.
//

module.exports = {
  singleQuote: true,
  trailingComma: 'es5',
};
